### PR TITLE
Misc typo fix in unmount

### PR DESCRIPTION
**Pull request by Akasurde**
## Description

Changed mount to unmount, since the error message is related to umount command.

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

**Review by fasaxc — APPROVED** [review]
LGTM

**Comment by Akasurde** [comment]
@fasaxc Thanks for the review and merge.

**Pull request merged**
